### ISSUE TITLE
Proposal: Upgrade Wifi APs

### ISSUE THREAD

**Issue by SuperQ** [noisebridge/infrastructure#125]
All but one APs in the space are 1st gen Unifi UAP-PRO models. These are from 2013 and older and only support 802.11n.

It would be nice to upgrade these for better wifi performance. The best bang for the buck right now is the [Unifi nanoHD](https://unifi-nanohd.ubnt.com/). They go for ~$180 each, we could use 2 or maybe 3 of them to retire 4 of the old APs.

**Comment by Borgaard** [comment]
If these are the items needed, I'll buy & ship to my house. Discussion in #finance-wg

**Comment by marcidy** [comment]
Now may not be the best time for this upgrade.  There's a very good chance we'll be moving in August.  I think limping along till we know that decision, the needs of the new space, and the post-move budget will make this more clear.  We could end up in a space half the size, for example, we have no way of knowing right now.

**Comment by SuperQ** [comment]
@marcidy That seems like a reasonable suggestion. Let's mark this closed for now, we can revisit based on new space needs.
