### ISSUE TITLE
IPv6 configuration

### ISSUE THREAD

**Issue by jmwilson** [noisebridge/infrastructure#128]
Monkeybrains supposedly offers IPv6 via DHCPv6-PD. I've set up DHCPv6-PD with Comcast on an EdgeRouter, and it should be pretty painless to double-stack the Noisebridge network.

I can make a PR to get the EdgeRouter to request a prefix and then hand out addresses, though I think there's a few of questions to sort out:
1. the size of our prefix - will have to ask Monkeybrains to be sure
1. any firewall policy we might want. I noticed there is no firewall config on the cycletrailer config. NAT is not true security, but it provides some separation compared to hosts that are fully on the internet.

**Comment by SuperQ** [comment]
Sounds like a great idea. Post here with what you find out from Monkeybrains. It would be nice to get a subnet we can route in so we have full IPv6 routing internally.

Yes, we'll want to have a default policy for normal access.

**Comment by SuperQ** [comment]
If you want, just propose the router changes here, we can try them out.

**Comment by jmwilson** [comment]
I did not hear from MB yet but based on https://twitter.com/monkeybrainsnet/status/648936091072856068 we have /56 prefix
