### ISSUE TITLE
Teach Ruth how to add and remove people from email aliases

### ISSUE THREAD

**Issue by ruthgrace** [noisebridge/infrastructure#148]
Hello,
As a weekly regular in the space and someone highly involved in fundraising and other Noisebridge initiatives, I'd really like the access and power to clean up the lists of people on all our email aliases (press@, fundraising@, etc.).

I've opened 3 issues recently for editing email alias membership (https://github.com/noisebridge/infrastructure/issues/135 https://github.com/noisebridge/infrastructure/issues/137 https://github.com/noisebridge/infrastructure/issues/140) and would really prefer to be able to do it myself. Right now I'd like to add Victoria and Nicole to fundraising@noisebridge.net

Thanks,
Ruth

**Comment by SuperQ** [comment]
You will still need to open issues and pull requests to update the aliases. This is required so we can track the requests to change them.

This is why I suggested fundraising be a self-managed email list in the first place, rather than a hard-coded alias.

**Comment by ruthgrace** [comment]
I'm happy to do that. Can I have access? Not just for fundraising but also for all the others. (For sure press@) Would it help if I got approval from the secretary?

**Comment by tdfischer** [comment]
> This is why I suggested fundraising be a self-managed email list in the first place, rather than a hard-coded alias.

How can we get that done?

**Comment by SuperQ** [comment]
It's pretty easy to create a mailman list. I can do that.

**Comment by marcidy** [comment]
The reason I didn't want a mailman list initially is because I don't want a
history to be saved.  Sensitive data was and still could be sent through to
address.

adding/removing is very low volume activity, I'm not clear why this is such
a problem?

**Comment by ruthgrace** [comment]
Oh, this is done! SuperQ taught me when he was last in town.

**Comment by ruthgrace** [comment]
Oh, this is done! SuperQ taught me when he was last in town.
