### ISSUE TITLE
move safespace reporting off pegasus

### ISSUE THREAD

**Issue by marcidy** [noisebridge/infrastructure#154]
Pegasus is open to everyone, so having a safespace reporting tool on it is not secure.

**Comment by marcidy** [comment]
need to move pegasus:/var/www/html/safespace/index.php somewhere and redirect the safespace url there.

Unclear where to put it tho.  Static site like the front page?  @rizend @SuperQ ?

**Comment by SuperQ** [comment]
We could add another virtual host to m3.

**Comment by marcidy** [comment]
Awesome, let me try to do that, thanks
