### ISSUE TITLE
#doorbell feed for the non-slackers

### ISSUE THREAD

**Issue by marcidy** [noisebridge/infrastructure#159]
is it possible to get the slack #doorbell log somewhere other than slack? doesn't have to be public as long as I can get to it.

any pointers to where that data flow is and I can probably do it.

**Comment by Borgaard** [comment]
It'd be a bit of an ugly misuse of Trello, but we can integrate with Slack
to create a card for each new message posted in a given channel. At the
very least you'd have a timestamp and a decent API to work with. Surely
it's better than appending new Slack messages to a wiki page. Yikes.

Do you have an API key for NB Slack?

The Slack/Discourse integrations I've found were only Discourse -> Slack
and not the other way around, unfortunately.

**Comment by hzeller** [comment]
The slack #doorbell channel actually just uses the API from earl, then makes the JSON data a bit more pretty.

 The API is on http://earl.local:3000/api/events  (I am not sure about the port, @SuperQ might remember as he has just set this up).
It pushes essentially jsonp callbacks whenever something is happening, with a very long HTTP timeout, so reconnects should be needed rarely.
I _thought_ I had documented that somewhere, but it should be easy to test manually: open a browser on it, then open door etc.

**Comment by hzeller** [comment]
Oh, and there is also just a simple TCP port to connect to and get the same events; makes it much simpler to interact with without having to implement a full HTTP client stack. Not sure if that is actually used for the #doorbell channel, as it makes it much easier to implement a robust slack integration.

**Comment by marcidy** [comment]
Awesome, thanks! ....and I cannot connect to earl or earl.noise from pegasus!  woe is me.

I assume there's no way to get the backlog without slack right now?  I can create my own logger off that endpoint on pegasus or whatever.

**Comment by hzeller** [comment]
yes, logging is intentionally sparse. Don't log things if not needed.

After the replacement of the earl-pi yesterday evening, there might still be lingering connection issues (e.g. the current #doorbell channel seems to not work yet). @superQ is looking into these.

**Comment by marcidy** [comment]
ok, if #doorbell isn't working right now then I can't get the info I need.  No one here knows if the sleeper got in this morning or somehow stayed over night.  It's amazing how so many things that happen rarely if ever happen all at once!  It's like the opposite of entropy.  Regardless, once earl is up 100% I'll implement this and close the isuse.

I'm only going to log what is in #doorbell so I can get at it when I need, aka whatever that API provides and is historized in slack.

**Comment by SuperQ** [comment]
We should send this information to IRC.

**Comment by SuperQ** [comment]
I've fixed earl so it's on the correct IP again. I used the same TCP/HTTP ports as was on the previous install.

**Comment by hzeller** [comment]
Note, the names of people who enter are not provided over the api, so the only thing we know is _if_ a member or philanthropist opened the door....

**Comment by marcidy** [comment]
I know, it's useful for investigation regardless.  thanks!

**Comment by SuperQ** [comment]
If people are interested in stats, there is a [dashboard](https://grafana.noisebridge.net/d/c-DDkA8mz/earl).

**Comment by marcidy** [comment]
I'm going to close this, never implemented anything but not really interested in it as others can do the monitoring/investigation.
