### ISSUE TITLE
noisebridge website a11y is worsening

### ISSUE THREAD

**Issue by old-noisebridger** [noisebridge/infrastructure#172]
Reviewing #171 led me to notice that the banners across the front page have text in images without alt tags. There are many other problems that should be fixed too, but text in images without alt tags is really egregious. I don't know how you kids are learning HTML these days but when I learned it in the 90s we used to **validate** our markup, and missing alt tags was, like, the most basic thing.

One nice thing about using MediaWiki is that you get a lot of accessibility best-practices for free. MediaWiki is far from perfect, but it is much better than the hand-written HTML on the static parts of your site presently.

Compare these static pages:
* http://wave.webaim.org/report#/https://www.noisebridge.net/ has 18 errors
* http://wave.webaim.org/report#/https://www.noisebridge.net/gala.html has 36 errors

to a MediaWiki page:
* http://wave.webaim.org/report#/https://www.noisebridge.net/Category:Events 3 errors (all 3 are "empty link text")

Please consider not using static pages, and regardless of if you use static pages or MediaWiki please try to keep your pages accessible.

If you are writing HTML and aren't using alt tags please read up, lmhtfy like maybe read https://www.w3.org/WAI/fundamentals/accessibility-intro/ or take this course https://www.udacity.com/course/web-accessibility--ud891 or something.

**Comment by SuperQ** [comment]
We could maybe add a CI pipeline check for this.

**Comment by lamebridge** [comment]
old noisebridger swooping in from elsewhere to complain about Noisebridge getting worse, but not actually taking action?  :shocked emoji:
