### ISSUE TITLE
Forward discuss forum announcements to announce mailing list

### ISSUE THREAD

**Issue by ruthgrace** [noisebridge/infrastructure#176]
What do people think? Would it be a good idea to automatically forward anything posted at https://discuss.noisebridge.info/c/announcements to the announce mailing list, with automatic admin approval?

**Comment by SuperQ** [comment]
Seems reasonable to me if there's a moderation requirement on discuss to avoid spam.

**Comment by ruthgrace** [comment]
I don't think there is. But there's a username associated so there's some
accountability.

**Comment by tdfischer** [comment]
There is moderation on discuss' announce category. I started looking into this this week but I don't have a direct answer from Discourse's side. I'll keep researching.

**Comment by SuperQ** [comment]
Sounds good. Thanks for the diligence.

**Comment by marcidy** [comment]
@tdfischer This is done yeah?

**Comment by marcidy** [comment]
This is done, other issues with annouce-list are raised in other issues, so im going to close this.
