### ISSUE TITLE
Add Tyler Maran to treasurer@noisebridge.net mailing list

### ISSUE THREAD

**Issue by tylermaran** [noisebridge/infrastructure#177]
tyler.maran@gmail.com or @themanmaran on discuss if you have any questions.

**Comment by Borgaard** [comment]
+1
Tyler's been fantastic in handling treasury data and reports. He should be added to treasurer@noisebridge.net

**Comment by Borgaard** [comment]
@ruthgrace would you mind adding Tyler to treasurer@noisebridge.net alias? 🙏

**Comment by ruthgrace** [comment]
Hey sorry, I've been meaning to but busy/frazzled. I'm not sure I can get
around to it in a timely manner.

**Comment by ruthgrace** [comment]
okay i'm looking now and i have zero recollection of where the alias stuff is and how to do it. i'm going to slack superq to ask. (sorry -- he showed me a month before baby and i didn't write it down :P)

**Comment by rizend** [comment]
The alias stuff for postfix is located in [roles/postfix/aliases](https://github.com/noisebridge/infrastructure/blob/master/roles/postfix/files/aliases).  #88 is one example of the aliases being updated that can be referenced.  Assuming you have the [ansible-vault](https://docs.ansible.com/ansible/latest/user_guide/vault.html) key stored in the correct location (`.vault-password`), you should be able to run `ansible-vault edit roles/postfix/aliases` to edit it.
