### ISSUE TITLE
Deploy reCAPTCHA for donate

### ISSUE THREAD

**Issue by marcidy** [noisebridge/infrastructure#188]
see:

https://discuss.noisebridge.info/t/weird-activity-on-stripe/836/17.  

Raising issue on donate repo to merge as well.

**Comment by marcidy** [comment]
see

https://github.com/noisebridge/donate.noisebridge.net/issues/112

**Comment by marcidy** [comment]
easy in flask, see here:
https://pusher.com/tutorials/google-recaptcha-flask

someone needs to sign-up for it as domain owner.  Not I.
https://www.google.com/recaptcha/admin/create

**Comment by SuperQ** [comment]
We could use the rack@lists.noisebridge.net email list.

**Comment by marcidy** [comment]
Unfortunately, it assumes that the signer-upper with a gmail account is an owner as well as some other email address you can change.

Actually maybe anyone can do it, i didn't check if it confirms with WHOIS or something.  I just wont be the one attached to it.

![image](https://user-images.githubusercontent.com/5845312/62484921-1ea71f80-b770-11e9-8084-129853d1e85d.png)
