### ISSUE TITLE
scheduling meetup to migrate donate and pair on deploy

### ISSUE THREAD

**Issue by ruthgrace** [noisebridge/infrastructure#193]
Hi @SuperQ , when would you be free for a video chat meetup to pair on deploy and also have all hands on deck to help migrate donate.noisebridge.net?

**Comment by SuperQ** [comment]
I'm available after 9:30 Monday morning.

**Comment by ruthgrace** [comment]
Assuming you mean Pacific time, let's go for 9:30am (in three hours)! I'll
send a Hangouts link on #rack in Slack closer to the time.

**Comment by ruthgrace** [comment]
We won't be able to migrate Donate with just me but maybe we can make a to
do list that others can asynchronously work on

**Comment by ruthgrace** [comment]
We're in the Hangouts now!

**Comment by elimisteve** [comment]
Record the session if it's OK with everyone!

**Comment by ruthgrace** [comment]
Ahh, it's too late, it happened this morning. We covered
* giving me (Ruth) the ansible vault password so i can update the email
aliases
* deploying the website and email aliases (these are all ansible commands
like what's in the readme but you can modify the host groups and tags for
the specific thing you want to deploy)
* starting work on getting the donate.noisebridge.net deploy in ansible --
@SuperQ @marcidy how far did you manage to get on this?

**Comment by marcidy** [comment]
I updated #195 with what we did and next steps, might as well keep that convo there.
