### ISSUE TITLE
Move fundraising@noisebridge.net to an address that can send and receive

### ISSUE THREAD

**Issue by marcidy** [noisebridge/infrastructure#201]
Speaking with Ryan, it seems like we do need an email address that can send and receive for the purposes of communicating with potential donors.  Is this feasible?

My initial objection was about sensitive data leaking because of the historization.  After discussion with Ryan, we can mitigate the sensitive data by moving messages manually or with a script.

Can we move fundraising to an inbox that can be run by one or more individuals?

**Comment by ruthgrace** [comment]
I personally like the convention of just CCing fundraising@ when replying to emails. Having an inbox can make it hard for people to know who sent what.

**Comment by ruthgrace** [comment]
I wonder if we can "send" email from fundraising@ via little green light?

**Comment by marcidy** [comment]
I agree.  It's a place where we need professionalism.  I really think we
need to carve out fundraising as a distinctly non-noisebridge thing that
intentionally has a recognized hierarchy.  Or not.

Like, Ryan is the only one trying to get donations.  And he says that
people who want to give donations need real correspondence.  And he's
probably right.  this is why we made the new front page.

We could use a whole separate domain, like a .org.  I think we already own
it.  let .net descend into the chaos it wants, and use .org as the "you get
86'd if you fuck this up" domain.  (ok, maybe not that harsh, but has some
real org to it.)

As far as this point goes, it's not super critical right now, but if we are
going to raise money, we do need some level of professionalism.

**Comment by ruthgrace** [comment]
Yes, please CC fundraising@ for any donation related communication so that
we don't step on each other's toes. Ideally Ryan should run who he is
asking by fundraising team so that we don't step on each other's toes and
get our messaging straight.

Ruth

**Comment by marcidy** [comment]
Right, but I still want to know if we can get the email working.

**Comment by ruthgrace** [comment]
I tried making fundraising@noisebridge.net my email in Little Green Light, however it doesn't get to my inbox in time for the 5 minute validity of the verification code. So we don't currently have a way of sending email from fundraising@noisebridge.net.

I still think that we shouldn't do it overall though

> I personally like the convention of just CCing fundraising@ when replying to emails. Having an inbox can make it hard for people to know who sent what.

having a shared inbox means everyone needs to be really good at signing their name at the end of emails, and we have to have really good coordination about who's going to reply to what. For example, if one person is the point of contact for a potential donor, then probably other people shouldn't jump into the email conversation.

**Comment by ruthgrace** [comment]
Matt and I chatted and we think it's a good idea to have personal @noisebridge.net emails (like, ruth@noisebridge.net) for members of the fundraising team when it gets to the point where we are seriously pursuing donor candidates. So there's no need for a shared inbox.

I'm going to close this issue for now. Let's revisit when more fundraising effort is happening, such that it's worth setting up some email system for multiple individuals. For now people can CC fundraising@noisebridge.net.

**Comment by ruthgrace** [comment]
oh, i was able to get LGL set up to email from fundraising@. Except, what it really does is email from little green light, and the reply-to is fundraising@:

<img width="945" alt="Screen Shot 2019-06-19 at 1 21 57 PM" src="https://user-images.githubusercontent.com/6069196/59797765-5b3cbb80-9295-11e9-87a9-26d7378dc4e4.png">

**Comment by marcidy** [comment]
it's hard to know how that will go over.  the lgl stuff looks a little
spammy.  If it goes over poorly that would kill any potential relationship
via spam filter.

**Comment by ruthgrace** [comment]
I agree, it's not great.
