### ISSUE TITLE
Where did Noisetor.net go?

### ISSUE THREAD

**Issue by elimisteve** [noisebridge/infrastructure#203]
It's been down for a couple months. Was it hosted on one of @patrickod's servers, or some NB server?

I need to stand it back up but should understand the previous setup. Will consult my notes from my meeting with Patrick in December.

**Comment by chazchaz101** [comment]
It was hosted on a VM we were paying for. Although I wasn't involved with the decision, I think it was turned off since it was a very large expense and we weren't able to clearly see that we're getting Noisetor specific donations to offset the cost.

**Comment by marcidy** [comment]
I thought the plan being to shut down the nodes, look at the financials, then make a determination to boot them back up if it made sense?  The servers were expensive from what I recall.  But that's like 6m old memory so I dont know if i remember correctly or if there were changes since.

**Comment by marcidy** [comment]
Closing, seems to be answered.  Feel free to re-open if there is more to do.  Thx.
