### ISSUE TITLE
Is the current contents of Pegasus in here?

### ISSUE THREAD

**Issue by elimisteve** [noisebridge/infrastructure#222]
I don't see the Say, Lang, etc `index.html` page for Mary, which I tweaked to point to FT Web, a web frontend for the FT I'm finishing testing and announcing today, and I want to avoid it getting wiped out from a later Ansible deploy of something to Pegasus.

Thanks.

**Comment by SuperQ** [comment]
No, most of that is probably not backed up anywhere. But doing an Ansible deploy won't wipe out anything that's not explicitly in Ansible.

**Comment by elimisteve** [comment]
Got it, thanks.
