### ISSUE TITLE
Oauth app created for discuss.noisebridge.info

### ISSUE THREAD

**Issue by sunjam** [noisebridge/infrastructure#270]
Ownership of the Oauth app has being transferred to noisebridge.  Please confirm transfer, then close this issue.

**Comment by sunjam** [comment]
Feel free to accept ownership transfer if you wish

**Comment by sunjam** [comment]
https://docs.github.com/en/developers/apps/managing-github-apps/transferring-ownership-of-a-github-app

I don't see a description of how to accept the transfer, but here is the documentation.

**Comment by SuperQ** [comment]
Thanks, I'll poke around and see if I can figure it out.

**Comment by SuperQ** [comment]
Found it! Approved.
