### ISSUE TITLE
Please add me (av_noisebridge) to the Noisebridge Gandi Team

### ISSUE THREAD

**Issue by sunjam** [noisebridge/infrastructure#278]
This is for domain and dns access.  Thanks.

**Comment by SuperQ** [comment]
DNS records are here: https://github.com/noisebridge/infrastructure/tree/master/files/coredns/zones

**Comment by sunjam** [comment]
No, add me because I control Noisebridge domains.

**Comment by sunjam** [comment]
Credentials were passed on to the Treasurer account.
