### ISSUE TITLE
Please add Kevin (bfb) to the Noisebridge Gandi Team

### ISSUE THREAD

**Issue by sunjam** [noisebridge/infrastructure#279]
This is for domain and dns access.  He has deployed a Jitsi instance we can use for videoconferencing.

**Comment by SuperQ** [comment]
If you just need to adjust DNS records, you don't need Gandi access. DNS records are in this repo, just open a PR.

https://github.com/noisebridge/infrastructure/tree/master/files/coredns/zones

**Comment by sunjam** [comment]
Closing, as bfb can handle any further steps needed.
