### ISSUE TITLE
Add discuss to grafana.noisebridge.net

### ISSUE THREAD

**Issue by sunjam** [noisebridge/infrastructure#280]
[Using this plugin](https://meta.discourse.org/t/prometheus-exporter-plugin-for-discourse/72666) we can now add https://discuss.noisebridge.info to grafana.noisebridge.net

Let me know on next steps needed.

**Comment by SuperQ** [comment]
Sounds like a good idea to me. The only real hard part is Discourse doesn't use standard authentication headers, so it's tricky to allow access. They're also too cool for documentation, and just have a discourse thread which is awful to read.

**Comment by sunjam** [comment]
I actually quite enjoy the way meta.discourse.org is setup.  You can point Prometheus to https://discuss.noisebridge.info/metrics

**Comment by SuperQ** [comment]
I get a 404 error for that URL.

**Comment by sunjam** [comment]
What is our ip address for the discuss whitelist?

It appears Prometheus is accessing the /metrics endpoint from a different
server. Therefore you need to allow this server to access the endpoint. To
do that, you need the external IP address of the server that Prometheus
runs on.

You then need to add this line to your app.yml file in the env: section:

DISCOURSE_PROMETHEUS_TRUSTED_IP_WHITELIST_REGEX: '(12\.34\.56\.78)'


In this example the IP address is 12.34.56.78, replace it with your own
address. Also make sure the indentation is correct.

After rebuilding the container, Prometheus should be able to access the
/metrics endpoint.

**Comment by sunjam** [comment]
If anyone wishes to follow up on this feel free to re-open
