### ISSUE TITLE
Unsure of how to proceed with changes on infrastructure.

### ISSUE THREAD

**Issue by sunjam** [noisebridge/infrastructure#287]
Ideally this system would shift away from how it is currently centralized and managed.

**Comment by hzeller** [comment]
@SuperQ is a staple in making sure our infrastructure works well. Could you elaborate on what your issue is instead of formulating it in a pre-2014 drama way, @sunjam ?

**Comment by sunjam** [comment]
Yeah, there is no specific system in place for handling these infrastructure issues.  Superq is non-responsive.  Issues are then sent to steve for review who is also non-responsive. We are all volunteers.  But this does not work.

**Comment by elimisteve** [comment]
Yes I haven't been involved with infra in a while. I support the idea of giving more people the ability to deploy. @SuperQ sounded open to it before provided that people used Docker or Ansible rather than crafting custom snowflake config files and the like, but I don't think he got around to giving more people access even if they promised to be responsible stewards.

**Comment by SuperQ** [comment]
Yes, I tried to coordinate training and such, but people either didn't respond or didn't show up to the scheduled times.

I also offered to train via reviews for changes people wanted. But nobody opened PRs to make changes.

**Comment by elimisteve** [comment]
How about @SuperQ writes a quick blurb that's a sort of Noisebridge SysAdmin Code of Conduct / Infrastructure Guild Induction Requirements, a mini tutorial/tour/intro to the infra, then hands over server access to more people?

**Comment by SuperQ** [comment]
I thought we had written some of that, maybe it was on discuss, but it seems like the Rack Guild has been deleted. 😕

**Comment by sunjam** [comment]
Rack guild was transitioned to rack tags, which can be used in all
categories

**Comment by elimisteve** [comment]
@SuperQ You and I talked a bit about what should be in such an agreement/commitment in our private Slack DM room; check there.

I think giving more people more control over NB's infrastructure is important, and I'm sure @sunjam agrees; please do so, @SuperQ.

**Comment by sunjam** [comment]
What I'm specifically interested in is distributing **ownership** of this github repository, plus all other repositories under [Noisebridge](https://github.com/noisebridge).  Ownership is what I want to see distributed between a multitude of users so issue can be addressed in a more timely manner amongst a more diverse population of volunteers.  I absolutely do not have to be amongst those people trusted with owning this repo.  I actually do not want to be. :smile:  Thank you for considering, and Happy Holidays!

**Comment by SuperQ** [comment]
There are already a bunch of long-standing Noisebridge members who are co-owners of the Noisebridge org and this repo. I am definitely not the only one. There are over 50 people who have write access to Noisebridge repos in general.

Most of them have their access hidden for privacy reasons.

**Comment by sunjam** [comment]
Ok.  How many owners are there?
