### ISSUE TITLE
Use cryptolog for all apache vhosts

### ISSUE THREAD

**Issue by patrickod** [noisebridge/infrastructure#4]
https://github.com/EFForg/cryptolog we should deploy this to prevent keeping identifying logs.

On top of this we should adopt very short-lived log retention. I'd be happy with 30 days maximum and then `shred`'ing them.

**Comment by SuperQ** [comment]
I'm not sure we can do this with Caddy's log handling, but it does have a built-in [ipmask](https://caddyserver.com/docs/log) feature that we could use to drop some bits from the request IP.

**Comment by rizend** [comment]
@SuperQ Is there anything more we want to do for this?

**Comment by SuperQ** [comment]
Nope, we setup caddy to do what we needed for IP filters.
