### ISSUE TITLE
Document target OS / Version for various servers (m3, m4, etc.)

### ISSUE THREAD

**Issue by rizend** [noisebridge/infrastructure#91]
I'd guess Debian Jessie was used for some servers at one point (see [roles/tor/tasks/main.yml](https://github.com/noisebridge/ansible/blob/d11aef7698e25a12b4901a1c99577e41f948be02/roles/tor/tasks/main.yml#L4) but also note that that role does not appear to be used anywhere), but I have not found any definitive documentation.

**Comment by SuperQ** [comment]
All of the `m*` servers and `pegasus` are currently Debian Stretch.

**Comment by marcidy** [comment]
@rizend Is there anything left outstanding on this?  I'm not sure if you have everything you want?

**Comment by rizend** [comment]
@marcidy Ideally we would still document the OS for `earl`, `smartpi`, and `cloud`.

**Comment by sunjam** [comment]
If help is needed on migrating to Debian Buster, we successfully backed up and upgraded Unicorn about two weeks ago.  Let us know.

**Comment by SuperQ** [comment]
Let's move the upgrade question to a new issue.
